@endpoint = https://0dexd9c19b.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/hola/
###

GET {{endpoint}}/hola/?spaceId=c0ae2d09-0e4d-40a0-bcee-dc8fd289a550
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Arlington",
    "name": "Bar Bao"
}
###
